/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(VSTSrcI16.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d268497db8770cec40e3f78715d2c21c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/VST/VSTSrcI16.h>
// pydoc.h is automatically generated in the build directory
//#include <VSTSrcI16_pydoc.h>

void bind_VSTSrcI16(py::module& m)
{
    using VSTSrcI16    = gr::VST::VSTSrcI16;    

    py::class_<VSTSrcI16, gr::block, gr::basic_block,
        std::shared_ptr<VSTSrcI16>>(m, "VSTSrcI16")

        .def(py::init(&VSTSrcI16::make),
           py::arg("resname") =  "RIO0",
           py::arg("iqrate") = 1e6,
           py::arg("carrierFreq") = 1e9,
           py::arg("reflevel") = 0)
		.def("stop",
		   & VSTSrcI16::stop)
		.def("set_carrierFreq",
		   & VSTSrcI16::set_carrierFreq,
           py::arg("carrierFreq") = 1e9)
		.def("set_reflevel",
		   & VSTSrcI16::set_reflevel,
           py::arg("reflevel") = 0)
		.def("set_iqrate",
		   & VSTSrcI16::set_iqrate,
           py::arg("iqrate") = 0);


}








